### ISSUE TITLE
Add support for HackRF and LimeSDR(mini)

### ISSUE THREAD

**Issue by Radiomix2000** [RUB-SysSec/DroneSecurity#1]

**Comment by nschllr** [comment]
Not planned

**Comment by klyed** [comment]
Considering how popular the hackRF is in comparison to the hardware used in the initial dev work.. might have a crack at this eventually Radiomix2000. It's not in my budget either to spent $1400 on a radio just to use this software to experiment.

Bandwidth was my largest concern. But if I do manage to figure it out I'll post a branch up.

**Comment by YGspike** [comment]
Hello, can you share the .raw file generated by the code？ just for test. thanks!
