### ISSUE TITLE
Does DJI send regular Wifi packet?

### ISSUE THREAD

**Issue by XBeg9** [RUB-SysSec/DroneSecurity#10]
Hi, 

Does it send regular wifi packets, like [IEEE 802.11](https://en.wikipedia.org/wiki/IEEE_802.11) ?

What I mean is, if it's just a standard 802.11 frames, then there could be a much cheaper option to catch it

**Comment by nschllr** [comment]
It depends, legacy DJI drones (e.g. Mavic Air 1) used WiFi as far as we know. The DJI drones which are using OcuSync transmit the DroneID packets as we described in the paper. But current DJI drones may also use WiFi and Bluetooth again to transmit these kind of data to comply with the new FAA regulations (see FAA UAS Remote Identification)

**Comment by YGspike** [comment]
Hello, can you share the .raw file generated by the code？ just for test. thanks!
