### ISSUE TITLE
Confusion about zcsequence_t and zcsequence_f,and  find_zc_angle.

### ISSUE THREAD

**Issue by Marcocd57** [RUB-SysSec/DroneSecurity#14]
first question:if we use LTE's point, zcsequence_t is directly frequency seq, in find_zc_seq()，author uses  zcsequence_t corralte with symbol_f in frequency,so i think author look zcsequence_t as frequency seq in there,but in estimate_channel() function author uses  zcsequence_f as frequency expected_signal , why ?
next question: in find_zc_angle(): i think author'aim is to find the initial constant phase offset, why use the angle value of zero freq point :angle(symbol_f[NCARRIERS//2]) as the estimation of angle? perhaps DJI dosenot send  ZC zeropoint,  so set this value to a constant real value,so the  receiver can use this point's  angle value as phase estimation directly?

**Comment by mrlnc** [comment]
We've been using time-domain and frequency-domain calculations in several stages and then sticked to what worked best for us. For `find_zc_angle` we feed the first symbol (index *`0`*, not angle 0) into the function.

If you're diving deeper into the code, I recommend setting `debug = True` for a GUI with plots. Also, there is a separate Matlab codebase that might be helpful: https://github.com/proto17/dji_droneid

**Comment by Marcocd57** [comment]
thank you！

**Comment by YGspike** [comment]
Hello, can you share the .raw file generated by the code？ just for test. thanks!
