### ISSUE TITLE
BladeRF 

### ISSUE THREAD

**Issue by therionkpi** [RUB-SysSec/DroneSecurity#17]
Hello! Do you plan to add bladerf?

**Comment by mrlnc** [comment]
There seem to be forks using BladeRF already, but we're not planning to add support to this repo, for now.

**Comment by Ganesh202** [comment]
> There seem to be forks using BladeRF already, but we're not planning to add support to this repo, for now.

can you share link of that fork

**Comment by YGspike** [comment]
Hello, can you share the .raw file generated by the code？ just for test. thanks!
