### ISSUE TITLE
DroneID packet emission on Mavic Air 2

### ISSUE THREAD

**Issue by MauriceSaccani** [RUB-SysSec/DroneSecurity#19]
hi,

you made a really impressive work! 

I am using your sw to get some droneID packets from a Mavic Air 2. I found some difficult to get those packets, i found and decoded some single droneID packets only saving demodulated data from my sdr and in some "random" bands and they looks like to be emitted very very rarely. When the drone use the first channel of 5.8 GHz band (center at 5735.5 MHz), i got some droneID packets centered at 5776.5 MHz emitted about every tens of second. In your paper the droneID packets should be emitted every 600 ms but i cant find them.

Do the droneID packets could be found in the same channel where other data (video ecc..) are sent? Because i searched there but i found no droneID packets.

thank you and br.

Maurice

**Comment by YGspike** [comment]
Hello, can you share the .raw file generated by the code？ just for test. thanks!
