### ISSUE TITLE
Recording of drone IQ data

### ISSUE THREAD

**Issue by Natur3sin321** [RUB-SysSec/DroneSecurity#21]
I would like to ask a few questions on recording of IQ data as my recorded signal is not as clean and neat as the sample files recorded.
How did you record the Ocusync 2.0 signal from Mavic air 2 and mini 2? What was signal bandwidth the 2 drone is transmitting at?

**Comment by nschllr** [comment]
The sample files are written by our live receiver, so there are just DroneID packets in there. I can't tell you if the our sample packets are from 2.4GHz or from the 5GHz band.

**Comment by YGspike** [comment]
Hello, can you share the .raw file generated by the code？ just for test. thanks!
