### ISSUE TITLE
Decoding failed for DJI Mavic Air 2 

### ISSUE THREAD

**Issue by waseem-arshad94** [RUB-SysSec/DroneSecurity#23]
Dear Sir;

I recorded the DJI MAVIC AIR 2 signal inside shielding room using adrv9361z7035 SDR board. I recorded the 3 Scenarios, one just ON (Mavic_air_2s_1000.fc32) and 2nd one turn on the propellers (Mavic_air_2s_1100.fc32) and 3rd take off (Mavic_air_2s_1110.fc32)and fly at the distance of 1m from the receiver. Whenever I run the offline receiver but decoding failed.I am sharing the complete log file and PNG files of in-spectrum testing. Kindly help needed. Please find the attachment.

[DJI_MAVIC_AIR_2.zip](https://github.com/RUB-SysSec/DroneSecurity/files/13752723/DJI_MAVIC_AIR_2.zip)

Thanks in advance

**Comment by nschllr** [comment]
If the screenshots show your entire recording, then no droneID packets are captured. Additionally, I believe that the sampling rate is incorrect; the captured packets appear to be the downlink, which should be 20MHz wide (as far as I know for that drone type).

**Comment by waseem-arshad94** [comment]
I set a sampling rate of 15.36 MHz.
