### ISSUE TITLE
hello how i can write my samples file

### ISSUE THREAD

**Issue by JackUzumbey** [RUB-SysSec/DroneSecurity#24]
I want to make a database of drone signals,
and I want to ask how do I write down the same samples as you?
can you do this with your code?

**Comment by nschllr** [comment]
Yes, all packets which are detected by the live receiver are stored in a file called `ext_droneid_{sample_rate}` [(see here)](https://github.com/RUB-SysSec/DroneSecurity/blob/9ff819843bee48fb140a0704ec78aff757896dea/src/droneid_receiver_live.py#L105C57-L105C57). All detected packets of the current session are appended to that file.
