### ISSUE TITLE
Inquiry about file creation in drone detection 

### ISSUE THREAD

**Issue by Ganesh202** [RUB-SysSec/DroneSecurity#26]
how did you create the sample files  of those two drones given in the repository and how can i make similar file for my DJI drone and test it  from the droneid_receiver_offline.py program.
and also, can I use LimeSDR instead of USRP for the live detection?

waiting for your reply.
Thank you

**Comment by nschllr** [comment]
Hi,
please have a look at our README:
`The samples were directly dumped from the first stage of the live receiver that detects candidate frames and performs no other data processing; it usually hands them directly to the rest of the code that you can test offline.`

To use a limeSDR you have to replace the respective code in `droneid_live_receiver.py`, but we didn't the a limeSDR.

**Comment by YGspike** [comment]
Hello, can you share the .raw file generated by the code？ just for test. thanks!
